# Autogenerated by nbdev

d = { 'settings': { 'branch': 'master',
                'doc_baseurl': '/test-release',
                'doc_host': 'https://tylere.github.io',
                'git_url': 'https://github.com/tylere/test-release',
                'lib_path': 'test_release'},
  'syms': {'test_release.core': {'test_release.core.foo': ('core.html#foo', 'test_release/core.py')}}}